lesson 17
YanaCavalian/A_level_Home_Work_JS pull request #6
Opened 2023-09-08 21:24 UTC by YanaCavalian

2023-09-09 12:58 UTC, cos1715 requested changes

2023-09-09 12:58 UTC, cos1715 commented on main.js
> +arr.sort((a, b) => a - b);
Why just arr
Looks like you should use arr1
Also make it a function

2023-09-09 12:58 UTC, cos1715 commented on main.js
> +      if (!uniqueArr.includes(upperCaseItem)) {
Not ideal solution

2023-09-09 13:37 UTC, YanaCavalian commented on main.js
> +arr.sort((a, b) => a - b);
// Return arr of numbers with values that are in range from 'from' param and to 'to' param
 function filterRange(arr, from, to) {
     return arr.filter(item => item >= from && item <= to);
 }

 const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
 const result = filterRange(arr, 3, 7);
 console.log(result);

 function sortArray(arr1) {
     return arr1.sort((a, b) => a - b);
 }

 const arr1 = [324, 32423, -3242, 544, 0, 23, -454, 22, 4];
 const sortedArr1 = sortArray(arr1);
 console.log(sortedArr1);

2023-09-11 08:28 UTC, cos1715 approved these changes

2023-09-11 11:15 UTC, merged